sudo: false
language: python
python:
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: Typhon
  password:
    secure: BilGD7T4nJZHQFtrenfltec6rPtVUCG62nkpQoDSTxK5iCkfVBU+gs3HcBHrdawOAe4epvF4K5Kn2Ww+DQul/VXU0KwgoQtEYw23DfWbykvaBhRnDzpIhR9Z3gBq4aKuehlajkZId+OcPLZCMcAlJB4Y3PwIEDPEWoEPD/47f9cCZFYwu4rWo02MqVkRC0Z2pt21LZVGouPfMc0dmuD0uvvajwIO9l/YfbxKni5sMrDQC/7uGjLRK8dXLwXItgL3i9u4ji/huk1mKbyQBEIGaxFTVJUvQ7Fo0Iop/iJ2q/bqPMG75Nwzvc0Qx1KYus6R+FLTn59ysE60Fh5ItXv7UsP1DR6mW8tDKg+d/W3qpCtmXmzqwaFrMmKcHIzrfrDOUjiaVitZWSYj1Llp0xDufV70ngyx92Bqawz0cAjjxNnBgdyqUPo6FS5UIA7tc4vtBulJ9cG1j6FwirDy1iuQpwdAyFO9MtBfKeHmfsn4nxX6f/ai+m+lh/WuRz6lkQGGcI/BPqzxqzkuEnX/cztogEwrrXToeFvisUzGktLcENwVgIVvIygZByR3zF+LY1XQwHEEEZbtnVyrLlBkQSWT8Eu+FTepYeW8pepAssB5Dnx5ySUX2G9YeFzQMbPHzWc0BF1rjaqR6SO7D1HbbBz/kn4PJEwv1cwHjyrwE0T/hHo=
  on:
    tags: true
